swagger: "2.0"

info:
  title: OpenAPIdev Specification example
  description: This is just an example.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
security:
  - api_key: []

paths:

  /echo:
    get:
      summary: Returns the senders messange
      operationId: "echo-GET"
      x-google-backend:
        address: https://sandbox-api-dev-n2tejwieia-uc.a.run.app/echo
      parameters:
        - in: query
          name: message
          type: string
          description: Message to be returned
      responses:
        "200":
          description: Return message.
          schema:
            type: object
            properties: 
              message:
                type: string
                description: Message content
      
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"